project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "overstock"
  sidebar:
    background: "#F5F5F5"
    logo: "images/logo.svg"
    pinned: true
    align: center
    tools:
      - icon: github
        text: "GitHub"
        menu:
          - text: Repository
            url: https://github.com/TrevorFrench/overstock
          - text: Profile
            url: https://github.com/TrevorFrench
      - icon: person-fill
        href: https://trevorfrench.com
        text: "Portfolio"
      - icon: linkedin
        href: https://www.linkedin.com/in/frenchtrevor/
        text: "LinkedIn"
      - icon: twitter
        href: https://twitter.com/TrvrFrnch
        text: "Twitter"
      - icon: youtube
        href: https://www.youtube.com/@TrevorFrench
        text: "Youtube"
      - icon: medium
        href: https://medium.com/@FrenchTrevor
        text: "Medium"
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: sql.qmd
        text: SQL and Database
      - href: excel.qmd
        text: Excel Basic Functions
      - href: marketing-analysis.qmd
        text: Marketing Analysis
      - href: scripting.qmd
        text: Scripting Test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

