---
title: "Marketing Analysis"
---

# Key Terminology

**Impressions:** How often your ad is shown. An impression is counted each time your ad is shown on a search result page

**Clicks:** When someone clicks your ad, like on the blue headline of a text ad. Only a small percentage of impressions lead to clicks.

**Conversions:** "An action that's counted when someone interacts with your ad (for example, clicks a text ad) and then takes an action that you've defined as valuable to your business, such as an online purchase. For this test, we will consider a conversion to be a purchase on our website."

**Ad Position:** The order in which your ad appears on a page in relation to other ads. An ad position of "1" means that your ad is the first ad on a page. Ads can appear on the top or bottom of a search results page.

**ROAS:** Return on Ad Spend - Total revenue / Ad Cost. Total revenue is the value of the conversions attributed to the ad spend incurred during a given time window.

# Situation

You are currently in position 3 of a paid text search keyword. The click-through rate (clicks per impressions) is 1% and the cost-per-click (CPC) is \$1. You can get into position 1 by paying \$2 CPC and would expect a CTR of 2%. In position 2, your CPC would be \$1.5 and you would expect a CTR of 1.5%. Conversion Rate (conversions per click) is 5% for all positions. (CvR) Gross margin per conversion is 20% (before advertising cost). Average Order (conversion) Value is \$200. (AOV)

The table below summarizes the above information:

| Ad Position | CTR   | CvR | Gross Margin | CPC    | AOV   |
|-------------|-------|-----|--------------|--------|-------|
| 1           | 2.00% | 5%  | 20%          | \$2.00 | \$200 |
| 2           | 1.50% | 5%  | 20%          | \$1.50 | \$200 |
| 3           | 1.00% | 5%  | 20%          | \$1.00 | \$200 |

# Questions

## Question 1

### Prompt

What is the cost per conversion in position 1?

### Answer

$$
CPC / CvR
$$

$$
$2.00 / .05 = $40.00
$$

## Question 2

### Prompt

What is the cost per conversion in position 2?

### Answer

$$
CPC / CvR
$$

$$
$1.50 / .05 = $30.00
$$

## Question 3

### Prompt

What is the cost per conversion in position 3?

### Answer

$$
CPC / CvR
$$

$$
$1.00 / .05 = $20.00
$$

## Question 4

### Prompt

If goal is to maximize absolute net profit, then which position you would want to be in?

### Answer

Position 3 as it has the lowest cost per conversion ($CPC/CvR$).

## Question 5

### Prompt

If goal is to maximize overall traffic, then which position you would want to be in?

### Answer

Position 1 as it has the highest click-through rate.

## Question 6

### Prompt

Compare that with the most profitable position (from the answer of the previous question) and calculate the % extra cost you would have to pay to sustain this position?

### Answer

You would need to pay 100% more to get into position 1 for the same amount of clicks in position 3.

## Question 7

### Prompt

What is return on ad spend (ROAS) of the additional conversions gained by moving from position 3 to position 2?

### Answer

$$
Total Revenue / Ad Cost
$$

$$
$200 / (1.50 / .05) = 6.67
$$
